# Generated by Django 3.1.6 on 2021-02-21 21:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название ингридиента', max_length=200, verbose_name='Ингридиент')),
                ('dimension', models.CharField(db_index=True, help_text='Единица измерения', max_length=200, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityOfIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Количество', verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('B', 'Завтрак'), ('D', 'Обед'), ('S', 'Ужин')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Название', max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(help_text='Изображение', upload_to='foodgram_images/', verbose_name='Изображение')),
                ('text', models.TextField(help_text='Текст рецепта', verbose_name='Текст рецепта')),
                ('time', models.IntegerField(help_text='Время приготовления', validators=[django.core.validators.MaxValueValidator(1440)], verbose_name='Время приготовления')),
                ('slug', models.SlugField(help_text='Идентификатор рецепта', unique=True)),
                ('author', models.ForeignKey(help_text='Автор', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredients', models.ManyToManyField(through='foodgram.QuantityOfIngredient', to='foodgram.Ingredient')),
                ('tag', models.ManyToManyField(related_name='Recipe', to='foodgram.Tag', verbose_name='Тег')),
            ],
        ),
        migrations.AddField(
            model_name='quantityofingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.recipe'),
        ),
    ]
