# Generated by Django 3.1.6 on 2021-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='default_title', help_text='Название', max_length=200),
            preserve_default=False,
        ),
    ]
