# Generated by Django 3.1.6 on 2021-02-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение', null=True, upload_to='foodgram_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='Recipe', to='foodgram.Tag', verbose_name='Тег'),
        ),
    ]
