# Generated by Django 3.1.6 on 2021-02-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20210223_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='Recipe', to='foodgram.Tag', verbose_name='Тег'),
        ),
    ]
