# Generated by Django 3.1.6 on 2021-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=b'GIF89a\x01\x00\x01\x00\x00\x00\x00!\xf9\x04', help_text='Изображение', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
