# Generated by Django 3.1.6 on 2021-02-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_auto_20210227_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
