# Generated by Django 3.1.6 on 2021-03-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0009_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite',
            new_name='recipe',
        ),
    ]
