# Generated by Django 3.1.6 on 2021-03-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0013_auto_20210306_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantityofingredient',
            name='ingredient',
            field=models.ForeignKey(help_text='Игредиент', on_delete=django.db.models.deletion.CASCADE, to='foodgram.ingredient', verbose_name='Игредиент'),
        ),
        migrations.AlterField(
            model_name='quantityofingredient',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт', on_delete=django.db.models.deletion.CASCADE, to='foodgram.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Изображение', upload_to='foodgram_images/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(help_text='Идентификатор рецепта', unique=True, verbose_name='Идентификатор рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Текст рецепта', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(db_index=True, help_text='Название', max_length=200, verbose_name='Название рецепта'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favorite unique'),
        ),
    ]
