# Generated by Django 3.1.6 on 2021-03-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0015_auto_20210312_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantityofingredient',
            name='ingredient',
            field=models.ForeignKey(help_text='Игредиент', on_delete=django.db.models.deletion.CASCADE, to='foodgram.ingredient', verbose_name='Игредиент'),
        ),
    ]
