# Generated by Django 3.1.6 on 2021-03-19 18:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0018_auto_20210316_1849'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('favorite', django.db.models.manager.Manager()),
            ],
        ),
    ]
