# Generated by Django 3.1.6 on 2021-03-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0019_auto_20210319_1805'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
            ],
        ),
    ]
