# Generated by Django 3.1.6 on 2021-03-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0020_auto_20210319_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipe', to='foodgram.Tag', verbose_name='Тег'),
        ),
    ]
