# Generated by Django 3.1.6 on 2021-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0021_auto_20210319_2313'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quantityofingredient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='QuantityOfIngredient unique together'),
        ),
    ]
