# Generated by Django 3.1.6 on 2021-03-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0023_auto_20210326_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoplist',
            options={'verbose_name_plural': 'Списки покупок'},
        ),
    ]
